# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(first_name: 'Valentino', last_name: 'Wong', email: 'valentino.wong@gmail.com', auth0_user_id: 'auth0|5da33c74a75b440d61f95f3d')
User.create(first_name: 'Cynthia', last_name: 'Koo', email: 'cyn.koo@joinhivehealth.com', auth0_user_id: 'auth0|5da4dea2ff3d2f0d454428a7')
User.create(first_name: 'Michelle', last_name: 'Bian', email: 'michelle.w.bian@joinhivehealth.com', auth0_user_id: 'auth0|5da4debbff3d2f0d454428a9')
User.create(first_name: 'Christopher', last_name: 'Wu', email: 'christopherwu10@joinhivehealth.com', auth0_user_id: 'auth0|5da4ded42f1c540d3e89e20e')
User.create(first_name: 'Zeus', last_name: 'Wu', email: 'zoi.demosthenes@joinhivehealth.com', auth0_user_id: 'auth0|5da4df126c89c60d4661b408')
User.create(first_name: 'Justin', last_name: 'Chiang', email: 'jchiang9@joinhivehealth.com', auth0_user_id: 'auth0|5da4df24f0ed020d510818d1')
User.create(first_name: 'Christine', last_name: 'Wang', email: 'christine.wang26@joinhivehealth.com', auth0_user_id: 'auth0|5da4df3ee2d34c0c4bf30df9')
User.create(first_name: 'Trudy', last_name: 'Li', email: 'li.trudy88@joinhivehealth.com', auth0_user_id: 'auth0|5da4df598777590d354c2719')
User.create(first_name: 'Rosa', last_name: 'Tse', email: 'rosaanntse@joinhivehealth.com', auth0_user_id: 'auth0|5da4df6f8777590d354c271a')
User.create(first_name: 'Edward', last_name: 'Lee', email: 'edwardlee31@joinhivehealth.com', auth0_user_id: 'auth0|5da4df89f0ed020d510818d7')
User.create(first_name: 'Andrew', last_name: 'Chang', email: 'achang0113@joinhivehealth.com', auth0_user_id: 'auth0|5da4dfa2ff3d2f0d454428bc')
User.create(first_name: 'Dina', last_name: 'Qiu', email: 'dina.qiu@joinhivehealth.com', auth0_user_id: 'auth0|5da4dfcef0ed020d510818db')
User.create(first_name: 'Dustin', last_name: 'Lo', email: 'dustinrlo@joinhivehealth.com', auth0_user_id: 'auth0|5da4dfe4f0ed020d510818dc')
User.create(first_name: 'Carolyn', last_name: 'Tai', email: 'carolytai@joinhivehealth.com', auth0_user_id: 'auth0|5da4e005b3053f0d56f4be7d')
User.create(first_name: 'Nina', last_name: 'Yang', email: 'nina.yang0208@joinhivehealth.com', auth0_user_id: 'auth0|5da4e01a3969d30d4fc4e116')
User.create(first_name: 'Michelle', last_name: 'Yip', email: 'myip2264@joinhivehealth.com', auth0_user_id: 'auth0|5da4e02fe2d34c0c4bf30e0d')
User.create(first_name: 'Spencer', last_name: 'Liu', email: 'xiayang.liu@joinhivehealth.com', auth0_user_id: 'auth0|5da4e04eb3053f0d56f4be87')
User.create(first_name: 'Amy', last_name: 'Wang', email: 'amywang09@joinhivehealth.com', auth0_user_id: 'auth0|5da4e06400abdf0d5177864b')
User.create(first_name: 'Will', last_name: 'Su', email: 'anephemeraleuphoria@joinhivehealth.com', auth0_user_id: 'auth0|5da4e07e8777590d354c2736')
User.create(first_name: 'Cindy', last_name: 'Guan', email: 'ms.cindyg@joinhivehealth.com', auth0_user_id: 'auth0|5da4e0923969d30d4fc4e123')
# User.create(first_name: 'Ellen', last_name: 'Liu', email: 'ellen.liu7@joinhivehealth.com', auth0_user_id: 21)
# User.create(first_name: 'Jenn', last_name: 'Lau', email: 'jlau5220@joinhivehealth.com', auth0_user_id: 22)
# User.create(first_name: 'Ingrid', last_name: 'Liu', email: 'ingrid.liu10@joinhivehealth.com', auth0_user_id: 23)
# User.create(first_name: 'Samuel', last_name: 'Shim', email: 'samuelhshim@joinhivehealth.com', auth0_user_id: 24)
# User.create(first_name: 'Minella', last_name: 'Capili', email: 'minella.capili@joinhivehealth.com', auth0_user_id: 25)
# User.create(first_name: 'Tim', last_name: 'Lentini', email: 'tim.c.lentini@joinhivehealth.com', auth0_user_id: 26)
# User.create(first_name: 'Anita', last_name: 'Yeung', email: 'anitawyeung@joinhivehealth.com', auth0_user_id: 27)
# User.create(first_name: 'Christina', last_name: 'Kim', email: 'cskim33090@joinhivehealth.com', auth0_user_id: 28)
# User.create(first_name: 'Radhika', last_name: 'Chopra', email: 'radhika.m.chopra@joinhivehealth.com', auth0_user_id: 29)
# User.create(first_name: 'Warren', last_name: 'Niu', email: 'warrenniu@joinhivehealth.com', auth0_user_id: 30)
# User.create(first_name: 'Tsiang', last_name: 'Pham', email: 'tsokha03@joinhivehealth.com', auth0_user_id: 31)
# User.create(first_name: 'Christopher', last_name: 'Tao', email: 'ctao08@joinhivehealth.com', auth0_user_id: 32)
# User.create(first_name: 'Jenny', last_name: 'Chen', email: 'jchen867@joinhivehealth.com', auth0_user_id: 33)
# User.create(first_name: 'Karina', last_name: 'Lin', email: 'karinalin@joinhivehealth.com', auth0_user_id: 34)
# User.create(first_name: 'Jeff', last_name: 'Chou', email: 'jchou762@joinhivehealth.com', auth0_user_id: 35)
# User.create(first_name: 'Kana', last_name: 'Yoo', email: 'kcyoo11@joinhivehealth.com', auth0_user_id: 36)
# User.create(first_name: 'Greg', last_name: 'Lull', email: 'gregorylull@joinhivehealth.com', auth0_user_id: 37)
# User.create(first_name: 'Bonny', last_name: 'Tsang', email: 'bonnytsang1@joinhivehealth.com', auth0_user_id: 38)
# User.create(first_name: 'Andrew', last_name: 'Lo', email: 'getlo06@joinhivehealth.com', auth0_user_id: 39)
# User.create(first_name: 'Jon', last_name: 'An', email: 'jonathan.an112@joinhivehealth.com', auth0_user_id: 40)
# User.create(first_name: 'Eileen', last_name: 'Ng', email: 'eileenng.en@joinhivehealth.com', auth0_user_id: 41)
# User.create(first_name: 'Winnie', last_name: 'Chan', email: 'winnielaa@joinhivehealth.com', auth0_user_id: 42)
# User.create(first_name: 'Elizabeth', last_name: 'Chin', email: 'kaedetou@joinhivehealth.com', auth0_user_id: 43)
# User.create(first_name: 'Chewy', last_name: 'Guo', email: 'christine.guo22@joinhivehealth.com', auth0_user_id: 44)
# User.create(first_name: 'David', last_name: 'Tong', email: 'menace1006@joinhivehealth.com', auth0_user_id: 45)
# User.create(first_name: 'Jenn', last_name: 'Mack', email: 'jmack04@joinhivehealth.com', auth0_user_id: 46)
# User.create(first_name: 'Ben', last_name: 'Wang', email: 'itzben@joinhivehealth.com', auth0_user_id: 47)
# User.create(first_name: 'Alice', last_name: 'Ng', email: 'aliceyxo@joinhivehealth.com', auth0_user_id: 48)
# User.create(first_name: 'William', last_name: 'Chan', email: 'wchchan@joinhivehealth.com', auth0_user_id: 49)
# User.create(first_name: 'Cindy', last_name: 'Qin', email: 'cindyqin@joinhivehealth.com', auth0_user_id: 50)
# User.create(first_name: 'Gloria', last_name: 'Chen', email: 'gloria.l.chen@joinhivehealth.com', auth0_user_id: 51)
# User.create(first_name: 'Nancy', last_name: 'Chan', email: 'nchan19@joinhivehealth.com', auth0_user_id: 52)
# User.create(first_name: 'Ruby', last_name: 'Lin', email: 'rlin89@joinhivehealth.com', auth0_user_id: 53)
# User.create(first_name: 'Dayna', last_name: 'Shi', email: 'dayna.shi@joinhivehealth.com', auth0_user_id: 54)
# User.create(first_name: 'Susan', last_name: 'Liu', email: 'susanwliu@joinhivehealth.com', auth0_user_id: 55)
# User.create(first_name: 'Tiffany', last_name: 'Chiu', email: 'tiffanyyhchiu@joinhivehealth.com', auth0_user_id: 56)
# User.create(first_name: 'Will', last_name: 'Im', email: 'william.im@joinhivehealth.com', auth0_user_id: 57)
# User.create(first_name: 'Julie', last_name: 'Zukina', email: 'jzukina@joinhivehealth.com', auth0_user_id: 58)
# User.create(first_name: 'Jeff', last_name: 'Chen', email: 'jeff@chen.lt', auth0_user_id: 59)
# User.create(first_name: 'Amanda', last_name: 'Nee', email: 'acnee18@joinhivehealth.com', auth0_user_id: 60)
# User.create(first_name: 'Matthew', last_name: 'Lee', email: 'matthew.lee143@joinhivehealth.com', auth0_user_id: 61)
# User.create(first_name: 'Tony', last_name: 'Shan', email: 'tshan614@joinhivehealth.com', auth0_user_id: 62)
# User.create(first_name: 'Andrew', last_name: 'Ludwig', email: 'andrewaludwig@joinhivehealth.com', auth0_user_id: 63)
# User.create(first_name: 'Christine', last_name: 'Hoang', email: 'christinelhoang@joinhivehealth.com', auth0_user_id: 64)
# User.create(first_name: 'Sam', last_name: 'Gomez', email: 'samgomez141@joinhivehealth.com', auth0_user_id: 65)
# User.create(first_name: 'Louis', last_name: 'Yuk', email: 'louishcyuk@joinhivehealth.com', auth0_user_id: 66)
# User.create(first_name: 'Chris', last_name: 'Wu', email: 'whoiswu@joinhivehealth.com', auth0_user_id: 67)
# User.create(first_name: 'Jessica', last_name: 'Li', email: 'jli388@joinhivehealth.com', auth0_user_id: 68)
# User.create(first_name: 'Heera', last_name: 'Gangaramani', email: 'heera.jg@joinhivehealth.com', auth0_user_id: 69)
# User.create(first_name: 'Melissa', last_name: 'Wu', email: 'melissa.q.wu@joinhivehealth.com', auth0_user_id: 70)
# User.create(first_name: 'Cyrus', last_name: 'Huang', email: 'cyrushuang472@joinhivehealth.com', auth0_user_id: 71)
# User.create(first_name: 'Yash', last_name: 'Kandoi', email: 'yashkandoi@joinhivehealth.com', auth0_user_id: 72)

Group.create(name: 'GymPact X', start_date: Date.parse("January 1, 2018"), end_date: Date.parse("April 22, 2018"), active: true, admin_id: User.find_by(email: 'valentino.wong@gmail.com').id)
Group.create(name: 'GymPact XI', start_date: Date.parse("May 7, 2018"), end_date: Date.parse("August 26, 2018"), active: true, admin_id: User.find_by(email: 'cyn.koo@joinhivehealth.com').id)


UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'cyn.koo@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'michelle.w.bian@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'christopherwu10@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'zoi.demosthenes@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'jchiang9@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'christine.wang26@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'li.trudy88@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'rosaanntse@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'edwardlee31@joinhivehealth.com').id)

UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'cyn.koo@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'michelle.w.bian@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'christopherwu10@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'zoi.demosthenes@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'jchiang9@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'christine.wang26@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'li.trudy88@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'rosaanntse@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'edwardlee31@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'achang0113@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'dina.qiu@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'dustinrlo@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'carolytai@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'nina.yang0208@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'myip2264@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'xiayang.liu@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'amywang09@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'anephemeraleuphoria@joinhivehealth.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'ms.cindyg@joinhivehealth.com').id)

Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id).id, week_number: 1, goal_days: 6)
Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id).id, week_number: 2, goal_days: 6)
Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id).id, week_number: 3, goal_days: 5)

Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id).id, week_number: 1, goal_days: 5)
Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id).id, week_number: 2, goal_days: 4)
Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id).id, week_number: 3, goal_days: 5)

Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'jchiang9@joinhivehealth.com').id).id, week_number: 1, goal_days: 4)
Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'jchiang9@joinhivehealth.com').id).id, week_number: 2, goal_days: 4)
Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'jchiang9@joinhivehealth.com').id).id, week_number: 3, goal_days: 3)

Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'jchiang9@joinhivehealth.com').id).id, week_number: 1, goal_days: 2)
Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'jchiang9@joinhivehealth.com').id).id, week_number: 2, goal_days: 2)
Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'jchiang9@joinhivehealth.com').id).id, week_number: 3, goal_days: 5)

Message.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, content: "Hello")
Message.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, content: "World")

Message.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'jchiang9@joinhivehealth.com').id, content: "Test Message #1")
Message.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'jchiang9@joinhivehealth.com').id, content: "Test Message #2")

Workout.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, datetime: Time.parse("2018-05-08 8:00 AM"), description: "3 Mile Run", approved: false)
Workout.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, datetime: Time.parse("2018-05-09 10:00 AM"), description: "5 Mile Run", approved: true)
Workout.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, datetime: Time.parse("2018-05-10 12:00 PM"), description: "10 Mile Run", approved: false)
Workout.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, datetime: Time.parse("2018-01-02 12:00 PM"), description: "15 Mile Run", approved: false)


Tag.create(name: 'Ab Workout')
Tag.create(name: 'Arm Bicycle')
Tag.create(name: 'Badminton')
Tag.create(name: 'Ballet')
Tag.create(name: 'Barre')
Tag.create(name: 'Baseball')
Tag.create(name: 'Basketball')
Tag.create(name: 'Biking/Spinning')
Tag.create(name: 'Bootcamp Class')
Tag.create(name: 'Boxing')
Tag.create(name: 'Cardio')
Tag.create(name: 'Climbing')
Tag.create(name: 'Crossfit')
Tag.create(name: 'Dance Class')
Tag.create(name: 'Dodgeball')
Tag.create(name: 'FitStar')
Tag.create(name: 'Football')
Tag.create(name: 'Golf')
Tag.create(name: 'Gym')
Tag.create(name: 'Handball')
Tag.create(name: 'HIIT')
Tag.create(name: 'Hiking')
Tag.create(name: 'Hockey')
Tag.create(name: 'Home Exercises')
Tag.create(name: 'Horseback Riding')
Tag.create(name: 'Hot Yoga')
Tag.create(name: 'Ice Skating')
Tag.create(name: 'Jiu Jitsu')
Tag.create(name: 'Kickball')
Tag.create(name: 'Krav Maga')
Tag.create(name: 'Lifting')
Tag.create(name: 'Non-Workout')
Tag.create(name: 'P90X')
Tag.create(name: 'P90X3')
Tag.create(name: 'Physical Therapy')
Tag.create(name: 'Pilates')
Tag.create(name: 'Ping Pong')
Tag.create(name: 'Roller Skating')
Tag.create(name: 'Rowing')
Tag.create(name: 'Rugby')
Tag.create(name: 'Running/Jogging')
Tag.create(name: 'Shooting')
Tag.create(name: 'Skateboarding')
Tag.create(name: 'Skiing/Snowboarding')
Tag.create(name: 'SLT')
Tag.create(name: 'Soccer')
Tag.create(name: 'Softball')
Tag.create(name: 'Stairs')
Tag.create(name: 'Surfing')
Tag.create(name: 'Swimming')
Tag.create(name: 'Tennis')
Tag.create(name: 'Tough Mudder')
Tag.create(name: 'Trapeze')
Tag.create(name: 'TRX')
Tag.create(name: 'Volleyball')
Tag.create(name: 'Walking Long Distance')
Tag.create(name: 'Yoga')

WorkoutTag.create(tag_id: Tag.find_by(name: 'Running/Jogging').id, workout_id: Workout.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, datetime: Time.parse("2018-05-08 8:00 AM"), description: "3 Mile Run").id)
WorkoutTag.create(tag_id: Tag.find_by(name: 'Running/Jogging').id, workout_id: Workout.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, datetime: Time.parse("2018-05-09 10:00 AM"), description: "5 Mile Run").id)
WorkoutTag.create(tag_id: Tag.find_by(name: 'Running/Jogging').id, workout_id: Workout.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, datetime: Time.parse("2018-05-10 12:00 PM"), description: "10 Mile Run").id)