# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(first_name: 'Valentino', last_name: 'Wong', email: 'valentino.wong@gmail.com', auth0_user_id: 1)
User.create(first_name: 'Cynthia', last_name: 'Koo', email: 'cyn.koo@gmail.com', auth0_user_id: 2)
User.create(first_name: 'Michelle', last_name: 'Bian', email: 'michelle.w.bian@gmail.com', auth0_user_id: 3)
User.create(first_name: 'Christopher', last_name: 'Wu', email: 'christopherwu10@gmail.com', auth0_user_id: 4)
User.create(first_name: 'Zeus', last_name: 'Wu', email: 'zoi.demosthenes@gmail.com', auth0_user_id: 5)
User.create(first_name: 'Justin', last_name: 'Chiang', email: 'jchiang9@gmail.com', auth0_user_id: 6)
User.create(first_name: 'Christine', last_name: 'Wang', email: 'christine.wang26@gmail.com', auth0_user_id: 7)
User.create(first_name: 'Trudy', last_name: 'Li', email: 'li.trudy88@gmail.com', auth0_user_id: 8)
User.create(first_name: 'Rosa', last_name: 'Tse', email: 'rosaanntse@gmail.com', auth0_user_id: 9)
User.create(first_name: 'Edward', last_name: 'Lee', email: 'edwardlee31@gmail.com', auth0_user_id: 10)
User.create(first_name: 'Andrew', last_name: 'Chang', email: 'achang0113@gmail.com', auth0_user_id: 11)
User.create(first_name: 'Dina', last_name: 'Qiu', email: 'dina.qiu@gmail.com', auth0_user_id: 12)
User.create(first_name: 'Dustin', last_name: 'Lo', email: 'dustinrlo@gmail.com', auth0_user_id: 13)
User.create(first_name: 'Carolyn', last_name: 'Tai', email: 'carolytai@gmail.com', auth0_user_id: 14)
User.create(first_name: 'Nina', last_name: 'Yang', email: 'nina.yang0208@gmail.com', auth0_user_id: 15)
User.create(first_name: 'Michelle', last_name: 'Yip', email: 'myip2264@gmail.com', auth0_user_id: 16)
User.create(first_name: 'Spencer', last_name: 'Liu', email: 'xiayang.liu@gmail.com', auth0_user_id: 17)
User.create(first_name: 'Amy', last_name: 'Wang', email: 'amywang09@gmail.com', auth0_user_id: 18)
User.create(first_name: 'Will', last_name: 'Su', email: 'anephemeraleuphoria@gmail.com', auth0_user_id: 19)
User.create(first_name: 'Cindy', last_name: 'Guan', email: 'ms.cindyg@gmail.com', auth0_user_id: 20)
User.create(first_name: 'Ellen', last_name: 'Liu', email: 'ellen.liu7@gmail.com', auth0_user_id: 21)
User.create(first_name: 'Jenn', last_name: 'Lau', email: 'jlau5220@gmail.com', auth0_user_id: 22)
User.create(first_name: 'Ingrid', last_name: 'Liu', email: 'ingrid.liu10@gmail.com', auth0_user_id: 23)
User.create(first_name: 'Samuel', last_name: 'Shim', email: 'samuelhshim@gmail.com', auth0_user_id: 24)
User.create(first_name: 'Minella', last_name: 'Capili', email: 'minella.capili@gmail.com', auth0_user_id: 25)
User.create(first_name: 'Tim', last_name: 'Lentini', email: 'tim.c.lentini@gmail.com', auth0_user_id: 26)
User.create(first_name: 'Anita', last_name: 'Yeung', email: 'anitawyeung@gmail.com', auth0_user_id: 27)
User.create(first_name: 'Christina', last_name: 'Kim', email: 'cskim33090@gmail.com', auth0_user_id: 28)
User.create(first_name: 'Radhika', last_name: 'Chopra', email: 'radhika.m.chopra@gmail.com', auth0_user_id: 29)
User.create(first_name: 'Warren', last_name: 'Niu', email: 'warrenniu@gmail.com', auth0_user_id: 30)
User.create(first_name: 'Tsiang', last_name: 'Pham', email: 'tsokha03@gmail.com', auth0_user_id: 31)
User.create(first_name: 'Christopher', last_name: 'Tao', email: 'ctao08@gmail.com', auth0_user_id: 32)
User.create(first_name: 'Jenny', last_name: 'Chen', email: 'jchen867@gmail.com', auth0_user_id: 33)
User.create(first_name: 'Karina', last_name: 'Lin', email: 'karinalin@gmail.com', auth0_user_id: 34)
User.create(first_name: 'Jeff', last_name: 'Chou', email: 'jchou762@gmail.com', auth0_user_id: 35)
User.create(first_name: 'Kana', last_name: 'Yoo', email: 'kcyoo11@gmail.com', auth0_user_id: 36)
User.create(first_name: 'Greg', last_name: 'Lull', email: 'gregorylull@gmail.com', auth0_user_id: 37)
User.create(first_name: 'Bonny', last_name: 'Tsang', email: 'bonnytsang1@gmail.com', auth0_user_id: 38)
User.create(first_name: 'Andrew', last_name: 'Lo', email: 'getlo06@gmail.com', auth0_user_id: 39)
User.create(first_name: 'Jon', last_name: 'An', email: 'jonathan.an112@gmail.com', auth0_user_id: 40)
User.create(first_name: 'Eileen', last_name: 'Ng', email: 'eileenng.en@gmail.com', auth0_user_id: 41)
User.create(first_name: 'Winnie', last_name: 'Chan', email: 'winnielaa@gmail.com', auth0_user_id: 42)
User.create(first_name: 'Elizabeth', last_name: 'Chin', email: 'kaedetou@gmail.com', auth0_user_id: 43)
User.create(first_name: 'Chewy', last_name: 'Guo', email: 'christine.guo22@gmail.com', auth0_user_id: 44)
User.create(first_name: 'David', last_name: 'Tong', email: 'menace1006@gmail.com', auth0_user_id: 45)
User.create(first_name: 'Jenn', last_name: 'Mack', email: 'jmack04@gmail.com', auth0_user_id: 46)
User.create(first_name: 'Ben', last_name: 'Wang', email: 'itzben@gmail.com', auth0_user_id: 47)
User.create(first_name: 'Alice', last_name: 'Ng', email: 'aliceyxo@gmail.com', auth0_user_id: 48)
User.create(first_name: 'William', last_name: 'Chan', email: 'wchchan@gmail.com', auth0_user_id: 49)
User.create(first_name: 'Cindy', last_name: 'Qin', email: 'cindyqin@gmail.com', auth0_user_id: 50)
User.create(first_name: 'Gloria', last_name: 'Chen', email: 'gloria.l.chen@gmail.com', auth0_user_id: 51)
User.create(first_name: 'Nancy', last_name: 'Chan', email: 'nchan19@gmail.com', auth0_user_id: 52)
User.create(first_name: 'Ruby', last_name: 'Lin', email: 'rlin89@gmail.com', auth0_user_id: 53)
User.create(first_name: 'Dayna', last_name: 'Shi', email: 'dayna.shi@gmail.com', auth0_user_id: 54)
User.create(first_name: 'Susan', last_name: 'Liu', email: 'susanwliu@gmail.com', auth0_user_id: 55)
User.create(first_name: 'Tiffany', last_name: 'Chiu', email: 'tiffanyyhchiu@gmail.com', auth0_user_id: 56)
User.create(first_name: 'Will', last_name: 'Im', email: 'william.im@gmail.com', auth0_user_id: 57)
User.create(first_name: 'Julie', last_name: 'Zukina', email: 'jzukina@gmail.com', auth0_user_id: 58)
User.create(first_name: 'Jeff', last_name: 'Chen', email: 'jeff@chen.lt', auth0_user_id: 59)
User.create(first_name: 'Amanda', last_name: 'Nee', email: 'acnee18@gmail.com', auth0_user_id: 60)
User.create(first_name: 'Matthew', last_name: 'Lee', email: 'matthew.lee143@gmail.com', auth0_user_id: 61)
User.create(first_name: 'Tony', last_name: 'Shan', email: 'tshan614@gmail.com', auth0_user_id: 62)
User.create(first_name: 'Andrew', last_name: 'Ludwig', email: 'andrewaludwig@yahoo.com', auth0_user_id: 63)
User.create(first_name: 'Christine', last_name: 'Hoang', email: 'christinelhoang@gmail.com', auth0_user_id: 64)
User.create(first_name: 'Sam', last_name: 'Gomez', email: 'samgomez141@gmail.com', auth0_user_id: 65)
User.create(first_name: 'Louis', last_name: 'Yuk', email: 'louishcyuk@gmail.com', auth0_user_id: 66)
User.create(first_name: 'Chris', last_name: 'Wu', email: 'whoiswu@gmail.com', auth0_user_id: 67)
User.create(first_name: 'Jessica', last_name: 'Li', email: 'jli388@gmail.com', auth0_user_id: 68)
User.create(first_name: 'Heera', last_name: 'Gangaramani', email: 'heera.jg@gmail.com', auth0_user_id: 69)
User.create(first_name: 'Melissa', last_name: 'Wu', email: 'melissa.q.wu@gmail.com', auth0_user_id: 70)
User.create(first_name: 'Cyrus', last_name: 'Huang', email: 'cyrushuang472@gmail.com', auth0_user_id: 71)
User.create(first_name: 'Yash', last_name: 'Kandoi', email: 'yashkandoi@gmail.com', auth0_user_id: 72)

Group.create(name: 'GymPact X', start_date: Date.parse("January 1, 2018"), end_date: Date.parse("April 22, 2018"), active: true, admin_id: User.find_by(email: 'valentino.wong@gmail.com').id)
Group.create(name: 'GymPact XI', start_date: Date.parse("May 7, 2018"), end_date: Date.parse("August 26, 2018"), active: true, admin_id: User.find_by(email: 'cyn.koo@gmail.com').id)


UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'cyn.koo@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'michelle.w.bian@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'christopherwu10@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'zoi.demosthenes@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'jchiang9@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'christine.wang26@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'li.trudy88@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'rosaanntse@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'edwardlee31@gmail.com').id)

UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'cyn.koo@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'michelle.w.bian@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'christopherwu10@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'zoi.demosthenes@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'jchiang9@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'christine.wang26@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'li.trudy88@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'rosaanntse@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'edwardlee31@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'achang0113@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'dina.qiu@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'dustinrlo@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'carolytai@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'nina.yang0208@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'myip2264@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'xiayang.liu@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'amywang09@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'anephemeraleuphoria@gmail.com').id)
UserGroup.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'ms.cindyg@gmail.com').id)

Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id).id, week_number: 1, goal_days: 6)
Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id).id, week_number: 2, goal_days: 6)
Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id).id, week_number: 3, goal_days: 5)

Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id).id, week_number: 1, goal_days: 5)
Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id).id, week_number: 2, goal_days: 4)
Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id).id, week_number: 3, goal_days: 5)

Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'jchiang9@gmail.com').id).id, week_number: 1, goal_days: 4)
Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'jchiang9@gmail.com').id).id, week_number: 2, goal_days: 4)
Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'jchiang9@gmail.com').id).id, week_number: 3, goal_days: 3)

Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'jchiang9@gmail.com').id).id, week_number: 1, goal_days: 2)
Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'jchiang9@gmail.com').id).id, week_number: 2, goal_days: 2)
Goal.create(user_group_id: UserGroup.find_by(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'jchiang9@gmail.com').id).id, week_number: 3, goal_days: 5)

Message.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, content: "Hello")
Message.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, content: "World")

Message.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'jchiang9@gmail.com').id, content: "Test Message #1")
Message.create(group_id: Group.find_by(name: 'GymPact X').id, user_id: User.find_by(email: 'jchiang9@gmail.com').id, content: "Test Message #2")

Workout.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, datetime: Time.parse("2018-05-08 8:00 AM"), description: "3 Mile Run", approved: false)
Workout.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, datetime: Time.parse("2018-05-09 10:00 AM"), description: "5 Mile Run", approved: true)
Workout.create(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, datetime: Time.parse("2018-05-10 12:00 PM"), description: "10 Mile Run", approved: false)

Tag.create(name: 'Ab Workout')
Tag.create(name: 'Arm Bicycle')
Tag.create(name: 'Badminton')
Tag.create(name: 'Ballet')
Tag.create(name: 'Barre')
Tag.create(name: 'Baseball')
Tag.create(name: 'Basketball')
Tag.create(name: 'Biking/Spinning')
Tag.create(name: 'Bootcamp Class')
Tag.create(name: 'Boxing')
Tag.create(name: 'Cardio')
Tag.create(name: 'Climbing')
Tag.create(name: 'Crossfit')
Tag.create(name: 'Dance Class')
Tag.create(name: 'Dodgeball')
Tag.create(name: 'FitStar')
Tag.create(name: 'Football')
Tag.create(name: 'Golf')
Tag.create(name: 'Gym')
Tag.create(name: 'Handball')
Tag.create(name: 'HIIT')
Tag.create(name: 'Hiking')
Tag.create(name: 'Hockey')
Tag.create(name: 'Home Exercises')
Tag.create(name: 'Horseback Riding')
Tag.create(name: 'Hot Yoga')
Tag.create(name: 'Ice Skating')
Tag.create(name: 'Jiu Jitsu')
Tag.create(name: 'Kickball')
Tag.create(name: 'Krav Maga')
Tag.create(name: 'Lifting')
Tag.create(name: 'Non-Workout')
Tag.create(name: 'P90X')
Tag.create(name: 'P90X3')
Tag.create(name: 'Physical Therapy')
Tag.create(name: 'Pilates')
Tag.create(name: 'Ping Pong')
Tag.create(name: 'Roller Skating')
Tag.create(name: 'Rowing')
Tag.create(name: 'Rugby')
Tag.create(name: 'Running/Jogging')
Tag.create(name: 'Shooting')
Tag.create(name: 'Skateboarding')
Tag.create(name: 'Skiing/Snowboarding')
Tag.create(name: 'SLT')
Tag.create(name: 'Soccer')
Tag.create(name: 'Softball')
Tag.create(name: 'Stairs')
Tag.create(name: 'Surfing')
Tag.create(name: 'Swimming')
Tag.create(name: 'Tennis')
Tag.create(name: 'Tough Mudder')
Tag.create(name: 'Trapeze')
Tag.create(name: 'TRX')
Tag.create(name: 'Volleyball')
Tag.create(name: 'Walking Long Distance')
Tag.create(name: 'Yoga')

WorkoutTag.create(tag_id: Tag.find_by(name: 'Running/Jogging').id, workout_id: Workout.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, datetime: Time.parse("2018-05-08 8:00 AM"), description: "3 Mile Run").id)
WorkoutTag.create(tag_id: Tag.find_by(name: 'Running/Jogging').id, workout_id: Workout.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, datetime: Time.parse("2018-05-09 10:00 AM"), description: "5 Mile Run").id)
WorkoutTag.create(tag_id: Tag.find_by(name: 'Running/Jogging').id, workout_id: Workout.find_by(group_id: Group.find_by(name: 'GymPact XI').id, user_id: User.find_by(email: 'valentino.wong@gmail.com').id, datetime: Time.parse("2018-05-10 12:00 PM"), description: "10 Mile Run").id)